AWSTemplateFormatVersion: '2010-09-09'
Description: Create VPC Flow Logs and S3 Bucket

Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VPC to enable Flow Logs for

Resources:
  FlowLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/vpc/flowlogs/${VpcId}'
      RetentionInDays: 7

  FlowLogRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FlowLogRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt FlowLogGroup.Arn

  FlowLog:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref VpcId
      ResourceType: VPC
      TrafficType: ALL
      LogGroupName: !Ref FlowLogGroup
      DeliverLogsPermissionArn: !GetAtt FlowLogRole.Arn

  FlowLogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-flow-logs-bucket # Change to your desired bucket name

  FlowLogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref FlowLogBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${FlowLogBucket}/*'
          - Effect: Allow
            Principal:
              Service: 'delivery.logs.amazonaws.com'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${FlowLogBucket}/AWSLogs/${AWS::AccountId}/*'

Outputs:
  FlowLogBucketName:
    Description: S3 Bucket for Flow Logs
    Value: !Ref FlowLogBucket
